blank_issues_enabled: false
contact_links:
  - name: QueryHub Discussions
    url: https://github.com/isasnovich/QueryHub/discussions
    about: Ask questions and share ideas outside of actionable issues.
